freebsd_instance:
  image_family: freebsd-13-0
  
task:
  env:
    PATH: $PATH:$HOME/.cargo/bin
    GITHUB_TOKEN: ENCRYPTED[78af20dcfc8b5d62df8898e3842f51b35db587f01377346375530a1feff1fefcf4ef4389f4fc69fdabbe557e4cc8d5d7]
    ARTIFACT_DIR: wasmtime-v5.0.0-x86_64-freebsd
  install_script: 
    - pkg install -y curl bash git-tiny gohugo jq
    - git submodule init
    - git submodule update
  script: 
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - cargo build --release
  upload_script: |
    #!/usr/bin/env bash
    if [[ "$CIRRUS_RELEASE" == "" ]]; then
      CIRRUS_RELEASE=$(curl -sL https://api.github.com/repos/$CIRRUS_REPO_FULL_NAME/releases/tags/$CIRRUS_TAG | jq -r '.id')
      echo "https://api.github.com/repos/$CIRRUS_REPO_FULL_NAME/releases/tags/$CIRRUS_TAG"
      if [[ "$CIRRUS_RELEASE" == "null" ]]; then
        echo "Failed to find a release associated with this tag! ($CIRRUS_RELEASE)"
        exit 0
      fi
    fi
    
    if [[ "$GITHUB_TOKEN" == "" ]]; then
      echo "Please provide GitHub access token via GITHUB_TOKEN environment variable!"
      exit 1
    fi
    
    file_content_type="application/octet-stream"
    files_to_upload=(
      target/release/wasmtime
      README.md
      LICENSE
    )

    mkdir wasmtime-v5.0.0-x86_64-freebsd
    for fpath in $files_to_upload
    do
      echo "Copying $fpath to $ARTIFACT_DIR"
      cp "$fpath" "$ARTIFACT_DIR/"
    done

    echo "Creating archive $ARTIFACT_DIR..."
    tar -zcvf "$ARTIFACT_DIR.tar.gz" "$ARTIFACT_DIR/"

    echo "Uploading $ARTIFACT_DIR.tar.gz..."
    name=$(basename "$ARTIFACT_DIR.tar.gz")
    url_to_upload="https://uploads.github.com/repos/$CIRRUS_REPO_FULL_NAME/releases/$CIRRUS_RELEASE/assets?name=$name"
    echo "Uploading to $url_to_upload"
    curl -X POST \
      --data-binary @$fpath \
      --header "Authorization: token $GITHUB_TOKEN" \
      --header "Content-Type: application/octet-stream" \
      $url_to_upload
    
